config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  resources :fornecedors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :fornecedor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fornecedors_controller.rb
class FornecedorsController < ApplicationController
  before_action :set_fornecedor, only: %i[ show edit update destroy ]

  # GET /fornecedors or /fornecedors.json
  def index
    @fornecedors = Fornecedor.all
  end

  # GET /fornecedors/1 or /fornecedors/1.json
  def show
  end

  # GET /fornecedors/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedors/1/edit
  def edit
  end

  # POST /fornecedors or /fornecedors.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to fornecedor_url(@fornecedor), notice: "Fornecedor was successfully created." }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedors/1 or /fornecedors/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to fornecedor_url(@fornecedor), notice: "Fornecedor was successfully updated." }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedors/1 or /fornecedors/1.json
  def destroy
    @fornecedor.destroy

    respond_to do |format|
      format.html { redirect_to fornecedors_url, notice: "Fornecedor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fornecedor_params
      params.require(:fornecedor).permit(:nome, :cnpj_cpf, :telefone, :email, :logradouro, :numero, :bairro, :cidade, :cep, :estado)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:nome, :tipo, :data_validade, :marca, :preco, :qtd, :fornecedor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/fornecedors/_form.html.erb
<%= form_with(model: fornecedor) do |form| %>
  <% if fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
        <% fornecedor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cnpj_cpf %>
    <%= form.text_field :cnpj_cpf %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :logradouro %>
    <%= form.text_field :logradouro %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fornecedors/edit.html.erb
<h1>Editing Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Show', @fornecedor %> |
<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fornecedors</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cnpj cpf</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Logradouro</th>
      <th>Numero</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Cep</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fornecedors.each do |fornecedor| %>
      <tr>
        <td><%= fornecedor.nome %></td>
        <td><%= fornecedor.cnpj_cpf %></td>
        <td><%= fornecedor.telefone %></td>
        <td><%= fornecedor.email %></td>
        <td><%= fornecedor.logradouro %></td>
        <td><%= fornecedor.numero %></td>
        <td><%= fornecedor.bairro %></td>
        <td><%= fornecedor.cidade %></td>
        <td><%= fornecedor.cep %></td>
        <td><%= fornecedor.estado %></td>
        <td><%= link_to 'Show', fornecedor %></td>
        <td><%= link_to 'Edit', edit_fornecedor_path(fornecedor) %></td>
        <td><%= link_to 'Destroy', fornecedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fornecedor', new_fornecedor_path %>

app/views/fornecedors/new.html.erb
<h1>New Fornecedor</h1>

<%= render 'form', fornecedor: @fornecedor %>

<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @fornecedor.nome %>
</p>

<p>
  <strong>Cnpj cpf:</strong>
  <%= @fornecedor.cnpj_cpf %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @fornecedor.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @fornecedor.email %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @fornecedor.logradouro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @fornecedor.numero %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @fornecedor.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @fornecedor.cidade %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @fornecedor.cep %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @fornecedor.estado %>
</p>

<%= link_to 'Edit', edit_fornecedor_path(@fornecedor) %> |
<%= link_to 'Back', fornecedors_path %>

app/views/layouts/_utilscripts.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
  
  <% flash.each do |f| %>
    toastr.options.timeOut = 1500;
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
  <% end %>
</script>
<% end %>

  <!-- jQuery CDN - Slim version (=without AJAX) -->
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
  <script type="text/javascript">
      $(document).ready(function () {
          $('#sidebarCollapse').on('click', function () {
              $('#sidebar').toggleClass('active');
          });
      });
  </script>

  <script type="text/javascript">
    function mask(o, f) {
      setTimeout(function() {
        var v = mphone(o.value);
        if (v != o.value) {
          o.value = v;
        }
      }, 1);
    }
    
    function mphone(v) {
      var r = v.replace(/\D/g, "");
      r = r.replace(/^0/, "");
      if (r.length > 10) {
        r = r.replace(/^(\d\d)(\d{5})(\d{4}).*/, "($1) $2-$3");
      } else if (r.length > 5) {
        r = r.replace(/^(\d\d)(\d{4})(\d{0,4}).*/, "($1) $2-$3");
      } else if (r.length > 2) {
        r = r.replace(/^(\d\d)(\d{0,5})/, "($1) $2");
      } else {
        r = r.replace(/^(\d*)/, "$1");
      }
      return r;
    }

    function mask_cpf(o, f) {
      setTimeout(function() {
        var v = mcpf(o.value);
        if (v != o.value) {
          o.value = v;
        }
      }, 1);
    }
    
    function mcpf(v) {
      var r = v.replace(/\D/g, "");
      
      if (r.length > 9) {
        r = r.replace(/^(\d\d\d)(\d{3})(\d{3})(\d{0,2}).*/, "$1.$2.$3-$4");
      } else if (r.length > 6) {
        r = r.replace(/^(\d\d\d)(\d{3})(\d{0,3}).*/, "$1.$2.$3");
      } else if (r.length > 3) {
        r = r.replace(/^(\d\d\d)(\d{0,3})/, "$1.$2");
      } else {
        r = r.replace(/^(\d*)/, "$1");
      }
      return r;
    }

    function mask_cep(o, f) {
      setTimeout(function() {
        var v = mcep(o.value);
        if (v != o.value) {
          o.value = v;
        }
      }, 1);
    }
    
    function mcep(v) {
      var r = v.replace(/\D/g, "");
      r = r.replace(/^0/, "");
      if (r.length > 5) {
        r = r.replace(/^(\d{0,5})(\d{0,3}).*/, "$1-$2");
      } else {
        r = r.replace(/^(\d*)/, "$1");
      }
      return r;
    }

    function mask_numero(o, f) {
      setTimeout(function() {
        var v = mnumero(o.value);
        if (v != o.value) {
          o.value = v;
        }
      }, 1);
    }
    
    function mnumero(v) {
      var r = v.replace(/\D/g, "");
      if (r.length > 11) {
        r = r.replace(/^(\d{0,11}).*/, "$1");
      } else {
        r = r.replace(/^(\d*)/, "$1");
      }
      return r;
    }
  </script>

  <script type="text/javascript">
      $(document).ready(function() {
        $('.remove-tag')
        .bind('ajax:beforeSend', function(evt) {
          evt.target.innerHTML = "Excluindo, aguarde ....";
          evt.target.disabled = true;
        })  
        .bind('ajax:error', function(evt) {
          evt.target.innerHTML = "Excluir";
          evt.target.disabled = false;
          toastr.options.timeOut = 1500;
          toastr.error('Erro: Alguma dependencia com outro Registro!');
        })      
      });
  </script>
 
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SysSistema</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>

    
    <style>
        #loadingoverlay {
            position: fixed;
            top: 0;
            z-index: 100;
            width: 100%;
            height: 100%;
            display: none;
            background: rgba(0,0,0,0.6);
        }

        .cv-spinner {
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .spinner {
            width: 40px;
            height: 40px;
            border: 4px #ddd solid;
            border-top: 4px #2e93e6 solid;
            border-radius: 50%;
            animation: sp-anime 0.8s infinite linear;
        }

        @keyframes sp-anime {
            0% {
                transform: rotate(0deg);
            }

            100% {
                transform: rotate(359deg);
            }
        }
   </style>
  </head>

  <body>

   <div id="loadingoverlay"> 
        <div class="cv-spinner">
            <span class="spinner"></span>
        </div>
    </div>
    
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar" >
            <div class="sidebar-header">
               <a href="" class="menulink"> <h4>SysSistema</h4> </a>
            </div>
            <ul class="list-unstyled components" class="menulink">
                <li>
                  <a href="" class="menulink"><i class="fa fa-users fa-fw"></i> Alunos</a>
                </li>
             
                <li>
                    <a href="#configuracaosubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle menulink">
                    <i class="fas fa-cog"></i> Configurações</a>
                    <ul class="collapse list-unstyled" id="configuracaosubmenu">
                     
                        <li>
                        <a href="" class="menulink"><i class="fas fa-users fa-fw"></i> Professores</a>
                        </li>
                       
                     

                    </ul>
                </li>
           
                
                <li>
                    <a href="" class="menulink"><i class="fa fa-question fa-fw"></i> Ajuda</a>
                </li>
            </ul>
       
         
           <ul class="list-unstyled CTAs">
                <li>
                   
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-primary colorprimarybtn">
                        <i class="fas fa-align-left"></i>
                        <span>Menu</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto colorprimarybtn" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="">Dados Pessoais</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

          <div class="content container-fluid">
              <div class="container-fluid">
              
                <%= yield %>
                
              </div>
          </div>
        </div>
    </div>
    <%= render :partial => 'layouts/utilscripts' %>
  </body>
</html>

app/views/layouts/applicationlogin.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>SysAlmoxarifado</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <style>
    @import "https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700";
    </style>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>

  <style>

    :root {
        --colorbasiclogin: #fff;
        --colortextlogin: var(--colortext-menu); 
    }

      body {
        background: #FFF;
        font-family: 'Roboto', sans-serif;
    }
  </style>
</head>

<body>
   <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #185a94;  margin-bottom: 0px;">
    </nav>
       
  

    <div class="wrapper">
        <div class="content container-fluid">
            <div class="container-fluid">
              <%= yield %>
            </div>
          </div>
    </div>

  <%= render :partial => 'layouts/utilscripts' %>
   
</body>

</html>

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :data_validade %>
    <%= form.date_select :data_validade %>
  </div>

  <div class="field">
    <%= form.label :marca %>
    <%= form.text_field :marca %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :qtd %>
    <%= form.number_field :qtd %>
  </div>

  <div class="field">
    <%= form.label :fornecedor_id %>
    <%= form.text_field :fornecedor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Tipo</th>
      <th>Data validade</th>
      <th>Marca</th>
      <th>Preco</th>
      <th>Qtd</th>
      <th>Fornecedor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.tipo %></td>
        <td><%= produto.data_validade %></td>
        <td><%= produto.marca %></td>
        <td><%= produto.preco %></td>
        <td><%= produto.qtd %></td>
        <td><%= produto.fornecedor_id %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @produto.tipo %>
</p>

<p>
  <strong>Data validade:</strong>
  <%= @produto.data_validade %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @produto.marca %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @produto.preco %>
</p>

<p>
  <strong>Qtd:</strong>
  <%= @produto.qtd %>
</p>

<p>
  <strong>Fornecedor:</strong>
  <%= @produto.fornecedor_id %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>